name: Release Common.Plugin
 
on:
  # push:
  #   branches: [ main ]
  #   paths: [ 
  #       'src/Commons/Common.Plugin/**',
  #       ]
  workflow_dispatch:
    inputs:
      libsToRelease:
        description: 'Libraries to release'
        required: true
        default: 'Common.Plugin'
        type: choice
        options:
        - Common.Plugin
        # - Common.Plugin.Utils
      preRelease:
        description: 'pre-release (def: false)'
        required: false
        default: false
        type: boolean     

jobs:
  filter:
    outputs:
      changed: ${{ steps.changes.outputs.changed }}  
    name: Detect Path
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
           filters: |
              changed:
                - 'src/Commons/Common.Plugin/**'
  release:
    needs: filter
    if: ${{ (needs.filter.outputs.changed == 'true' && github.event_name == 'push') || (inputs.libsToRelease == 'all') ||  (inputs.libsToRelease == 'Common.Plugin')}}
    uses: pietroserrano/plugutopia/.github/workflows/nuget.yml@main
    with:
      NET_VERSION: '8.x'
      PROJECT_DIRECTORY_NAME: src/Commons/Common.Plugin
      PROJECT_FILENAME: Common.Plugin.csproj
      PREFIX_TAG: PlugUtopia.Plugin
      RELEASE: PlugUtopia.Plugin
      IS_PRE_RELEASE: ${{ contains(inputs.preRelease, 'true') }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
    secrets: inherit
    
  release2:
    needs: filter
    if: ${{ (needs.filter.outputs.changed == 'true' && github.event_name == 'push') || (inputs.libsToRelease == 'all') ||  (inputs.libsToRelease == 'Common.Plugin.Utils')}}
    uses: pietroserrano/plugutopia/.github/workflows/nuget.yml@main
    with:
      NET_VERSION: '8.x'
      PROJECT_DIRECTORY_NAME: src/Commons/Common.Plugin.Utils
      PROJECT_FILENAME: Common.Plugin.Utils.csproj
      PREFIX_TAG: PlugUtopia.Plugin.Tools
      RELEASE: PlugUtopia.Plugin.Tools
      IS_PRE_RELEASE: ${{ contains(inputs.preRelease, 'true') }}
      NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      NUGET_SOURCE: https://nuget.pkg.github.com/pietroserrano/index.json
    secrets: inherit    
